Make configurable basic UI WebSocket request path and move UI to a template file
jmalloc/echo-server pull request #32
Opened 2023-11-29 07:44 UTC by maximthomas

2024-01-31 00:21 UTC, onedr0p requested changes

2024-01-31 00:21 UTC, onedr0p commented on cmd/echo-server/main.go
> +		serveFromntend(wr)
```suggestion
		serveFrontend(wr)
```

2024-01-31 00:21 UTC, onedr0p commented on cmd/echo-server/main.go
> +func serveFromntend(wr http.ResponseWriter) {
```suggestion
func serveFrontend(wr http.ResponseWriter) {
```

2024-06-17 13:32 UTC, onedr0p approved these changes

2024-06-18 21:19 UTC, jmalloc commented
Thanks folks. I am happy to merge this, but out of curiosity, would your particular use case also be solved if the frontend's `wss://` URL were to use to the same path at which the frontend is served?

2024-06-19 11:29 UTC, maximthomas commented
Hi @jmalloc, 
I've encountered a problem where the echo-server should be deployed behind a reverse proxy. There is another application behind the same proxy that should be accessible using the root path. So, I proposed the option to eliminate the conflict.

2024-06-30 22:39 UTC, jmalloc commented
Thanks again! Would PR https://github.com/jmalloc/echo-server/pull/35 also solve your use case?

2024-07-01 03:32 UTC, maximthomas commented
@jmalloc Not quite. PR #35 is about ws and sse endpoints, and the current PR is about the UI

2024-07-01 08:03 UTC, merged

2024-07-01 08:08 UTC, jmalloc commented
I've released [v0.3.7](https://github.com/jmalloc/echo-server/releases/v0.3.7), which adds the `WEBSOCKET_ROOT` environment variable, which is very similar to the `FRONTEND_WS_PATH` variable added by this PR. It combines the behaviour of this PR with that of #35, wherein the path that the `.ws` UI is served from is also added to the websocket URL. This should also fix #24.